# CodeDeploy 배포 명세서
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/techinsights

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ec2-user
