services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres-local
    restart: always
    environment:
      POSTGRES_USER: local-user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: techinsights_db
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api-local
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/techinsights_db
      - SPRING_DATASOURCE_USERNAME=local-user
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=local
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-local
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: always

volumes:
  db_data:
