name: Batch - githubTrendingJob

on:
  workflow_dispatch:

jobs:
  github-trending:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_batch-ssm-runner.yml
    with:
      job_name: githubTrendingJob
    secrets:
      AWS_IAM_ROLE_FOR_OIDC: ${{ secrets.AWS_IAM_ROLE_FOR_OIDC }}
      EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
      RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
