name: Run Spring Batch Job on Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  run-batch-job:

    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build batch module
        run: ./gradlew :batch:build -x test

      - name: Run batch application
        env:
          SPRING_PROFILES_ACTIVE: local
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          java -Dspring.profiles.active=local -jar batch/build/libs/batch-0.0.1-SNAPSHOT.jar --spring.batch.job.name=crawlPostJob run.id=${{ github.run_id }}